-- create
CREATE TABLE MENU (
  Food TEXT NOT NULL,
  Price INTEGER NOT NULL
);

-- insert
INSERT INTO MENU VALUES ('BBQ', 100);
INSERT INTO MENU VALUES ('CHICKEN', 150);
INSERT INTO MENU VALUES ('SISIG', 121);
INSERT INTO MENU VALUES ('FISH', 152);

-- fetch 
SELECT * FROM MENU WHERE Food  = 'SISIG';
